using J2BIOverseasOps.Pages.BuildingWork;
using log4net;
using OpenQA.Selenium;
using TechTalk.SpecFlow;

namespace J2BIOverseasOps.StepDefs.BuildingWork
{
    [Binding]
    public sealed class FullRecordOverviewStepDefs : BaseStepDefs
    {
        private readonly FullRecordOverviewComponent _recordOverview;

        public FullRecordOverviewStepDefs(IWebDriver driver, ILog log,IRunData rundata) : base(driver, log)
        {
            _recordOverview = new FullRecordOverviewComponent(driver, log,rundata);
        }

        [Then(@"I verify the building work Id field starts with ""(.*)""")]
        public void ThenIVerifyTheBuildingWorkIdFieldStartsWith(string expected)
        {
            _recordOverview.VerifyBwIdStartsWith(expected);
        }

        [Then(@"I verify the building work Id field contains the IATA code as ""(.*)""")]
        public void ThenIVerifyTheBuildingWorkIdFieldContainsTheIATACodeAs(string iataCode)
        {
            _recordOverview.VerifyIataCodeInId(iataCode);

        }

        [Then(@"I verify the building work Id field ends with the number")]
        public void ThenIVerifyTheBuildingWorkIdFieldEndsWithTheNumber()
        {
            _recordOverview.VerifyBwIdNumber();
        }

        [Then(@"I verify the building work Id is not changed")]
        public void ThenIVerifyTheBuildingWorkIdIsNotChanged()
        {
            _recordOverview.VerifyBwId();
        }

        [Then(@"I verify the record creation date contains today's date with the format DD/MM/YYYY")]
        public void ThenIVerifyTheRecordCreationDateContainsTodaySDateWithTheFormat()
        {
            _recordOverview.VerifyRecordCreationDateAsTodays();
        }

        [Then(@"I verify the Recorded by field contains my ""(Name|Job Title)""")]
        public void ThenIVerifyTheRecordedByFieldContainsMy(string nameTitle)
        {
            _recordOverview.VerifyNameTitleField(nameTitle);
        }

        [Then(@"I verify the form completion date contains today's date with the format DD/MM/YYYY")]
        public void ThenIVerifyTheFormCompletionDateContainsTodaySDateWithTheFormatDDMMYYYY()
        {
            _recordOverview.VerifyFormCompletionDate();
        }


        [When(@"I note down the following auto generated record overview values on the building work page")]
        public void WhenINoteDownTheFollowingValuesOnTheBuildingWorkPage(Table table)
        {
            _recordOverview.NoteDownAutoGeneratedFields(table);
        }

        [Then(@"I verify the following auto generated record overview values on the building work page")]
        public void ThenIVerifyTheFollowingAutoGeneratedRecordOverviewValuesOnTheBuildingWorkPage(Table table)
        {
            _recordOverview.VerifyAutoGeneratedFields(table);
        }

        [Then(@"I verify the Destination as ""(.*)"", Resort as ""(.*)"" and property as ""(.*)"" on building works overview")]
        public void ThenIVerifyTheDestinationAsResortAsAndPropertyAsOnBuildingWorksOverview(string destination, string resort, string property)
        {
            _recordOverview.VerifyBwPropertyDetailsOverviewSection(destination, resort, property);
        }

        [Then(@"I verify the value of following field on the Overview section:")]
        public void ThenIVerifyTheValueOfFollowingFieldOnTheOverviewSection(Table table)
        {
            _recordOverview.VerifyValueOfFields(table);
        }



    }
}